application: topicsns
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /img
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: javascript

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest